# Language
language: en
# Camera usernames
cameraNames: []
# Whether to switch players in turns
autoSwitchPlayer: true
# Interval for switching players (minutes)
switchPlayerInterval: 10
# Whether to fix the camera position when no players are online
fixedCameraPosition:
  - name: "Default"
    world: "world"
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
# Timeout for communication with the client (unit: seconds)
networkTimeout: 10