name: AutoStreamingAssistant
version: '${version}'
main: cn.cutemc.autostreamingassistant.bukkit.AutoStreamingAssistant
api-version: '1.20'
authors: [lushangkan]
description: A Automated Live Streaming Assistant Bukkit Plugin.
website: https://cutemc.cn
